---
title: Control de Versions *Git*
subtitle: "Sessió 4 - Curs zero d'Informàtica"
author: 
  - name: Josep Alòs
logo: "/figures/corporative/institute.png"
format: 
  revealjs:
    transition: fade
    slide-number: true
    incremental: true 
    chalkboard: false
    footer: "Sessió 4 · Curs zero d'Informàtica [🏠](/index.html)</a>"
editor: visual

mermaid:
  theme: forest

execute:
  freeze: auto
  echo: false
---

# Referències: commits, tags, i branques

## Commits

**Recordatori:**

Cada commit té un identificador únic.

```         
git log --oneline
a31f42c Afegeix README
8b7291a Afegeix dades
f42c812 Crea projecte
```

`HEAD` és una referència al commit que estem consultant actualment

``` tikz
%%| filename: commits
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30}
]
    \node[commit] (A) {f42c812\\Crea projecte};
    \node[commit, right = of A] (B) {8b7291a\\Afegeix dades};
    \node[commit, right = of B] (C) {a31f42c\\Afegeix README};
    \node[head, below = of C] (H) {HEAD};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (H.north) -- (C.south);
\end{tikzpicture}
```

## Tags

Git ens permet marcar certs commits amb noms fàcils de recordar. Aquests noms s'anomenen *tags*.

Per exemple:

```         
git tag v1.0
```

``` tikz
%%| filename: tags
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small}
]
    \node[commit] (A) {f42c812};
    \node[commit, right = of A] (B) {8b7291a};
    \node[commit, right = of B] (C) {a31f42c};
    \node[head, below = of C] (H) {HEAD};
    \node[tag]    (T) [above=of B] {v1.0};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (H.north) -- (C.south);
    \draw[->] (T.south) -- (B.north);
\end{tikzpicture}
```

**Rarament modificarem a quin commit fa referència un tag.**

És habitual utilitzar-los per marcar versions importants.

## Tags

Ara podem utilitzar `v1.0` enlloc de l'ID del commit:

```         
git show v1.0
git diff v1.0..HEAD
```

Podem veure els tags amb `git tag`[^1].

[^1]: O explícitament amb `git tag --list` o `git tag -l`

## Branques

Fins ara hem tingut una única línia d'història.

Imaginem que estem treballant en una nova versió del projecte i algú troba un error en una versió anterior.

**Podem treballar per arreglar aquest error sense interferir amb el desenvolupament actual?**

## Branques

Git ens permet crear diferents camins dins de la història del projecte.

``` tikz
%%| filename: branches-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [above right=of C] {D\\nova funcionalitat};
    \node[commit] (E) [right=of D] {E\\nova funcionalitat};
    \node[commit] (F) [below right=of C] {F\\correcció};
    \node[commit] (G) [right=of F] {G\\correcció};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
\end{tikzpicture}
```

Les dues branques comparteixen la història fins al punt on se separen.

A partir d'aquest punt, podem fer commits diferents en cadascuna.

## Branques

Una **branca** és un nom que utilitzem per seguir una línia de la història del projecte.

*S'assembla a un tag, però es va actualitzant cada commit que fem.*

Per defecte, Git crea una branca anomenada `master` o `main`[^2].

[^2]: No és especial, simplement es crea automàticament.

``` tikz
%%| filename: branches-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [above right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right=of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

## Branques

Podem veure les branques del repositori amb:

```         
git branch
```

Podem crear una nova branca (e.g. `fix-error`) amb:

```         
git branch fix-error
```

i començar a treballar sobre aquesta branca amb:

```         
git switch fix-error
```

**Nota** podem fer la nova branca i canviar-hi amb una sola comanda fent servir `git switch -c fix-error`.

Per tornar a la branca `main` fem `git switch main`.

## Branques: el multivers de Git

Una branca no és una còpia sencera del projecte.

És una manera de continuar la història del projecte per un camí diferent.

``` tikz
%%| filename: branches-3
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [above right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right=of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

Les dues branques tenen en comú els commits anteriors a la separació.

Els commits posteriors poden ser diferents.

## Commits, tags, i branques

Podem veure aquests conceptes com diferents maneres de referir-nos a la història

``` tikz
%%| filename: commits-tags-branches
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [above right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right=of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \node[tag] (v1) [above = of C] {v1.0};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (v1) -- (C);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

- Commit: un punt concret en la història.
- Tag: un nom a un commit concret.
- Branca: un nom que va avançant per una línia de la història.

. . .

Podem veure el graf fent servir:

```         
git log --all --graph --oneline --decorate
```

# Unificant la història

Amb les branques podem desenvolupar en paral·lel parts del nostre projecte, arreglar errors en versions anteriors, etc.

**No volem tenir N línies d'història diferents del nostre projecte, en algun punt volem unificar-les tot.**

Git no només ens permet divergir la nostra història sinó també convergir-la.

## Merge de branques {.smaller}

``` tikz
%%| filename: merge-before
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

En aquest punt, tenim l'error arreglat i volem unificar `main` amb `fix-error`.

Podem fer dues coses:

- Portar els canvis de `fix-error` cap a `main`
- Portar els canvis de `main` cap a `fix-error`

. . .

**El merge sempre es fa des de la branca que volem actualitzar.**

## Merge de branques {.smaller}

``` tikz
%%| filename: merge-before-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

Portarem els canvis de `fix-error` cap a `main`:

1.  Ens situem a la branca `main`
2.  Creem un **commit de merge** que té dos *antecessors*:
    - El commit al que fa referència `main`
    - El commit al que fa referència `fix-error`
3.  Actualitzem `main` per a que faci referència al **commit de merge**

. . .

El primer pas el fem amb `git switch main`, i els passos 2 i 3 els fem amb `git merge fix-error`.

## Merge de branques

`git switch main` ens situa a:

``` tikz
%%| filename: merging-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    \node[head] (head) [above of=main] {HEAD};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
    \draw[->] (head) -- (main);
\end{tikzpicture}
```

## Merge de branques

`git merge fix-error` ens situa a:

``` tikz
%%| filename: merging-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};
    \node[commit] (H) [right=of E] {H};

    \node[branch] (main) [above=of H] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    \node[head] (head) [above of=main] {HEAD};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (E.east) -- (H.west);
    \draw[->] (G.east) -- (H.west);
    \draw[->] (main) -- (H);
    \draw[->] (fix-error) -- (G);
    \draw[->] (head) -- (main);
\end{tikzpicture}
```

::: aside
`H` és el commit de merge.
:::

## Merge de branques

**Quiz** Si fem `git log main`, quins commits veurem? I `git log fix-error`?

``` tikz
%%| filename: merged
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};
    \node[commit] (H) [right=of E] {H};

    \node[branch] (main) [above=of H] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (E.east) -- (H.west);
    \draw[->] (G.east) -- (H.west);
    \draw[->] (main) -- (H);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

## Merge de branques: fast-forward

``` tikz
%%| filename: ff-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};
    \node[commit] (H) [right=of E] {H};

    \node[branch] (main) [above=of H] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    \node[head] (head) [above of=main] {HEAD};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (E.east) -- (H.west);
    \draw[->] (G.east) -- (H.west);
    \draw[->] (main) -- (H);
    \draw[->] (fix-error) -- (G);
    \draw[->] (head) -- (main);
\end{tikzpicture}
```

Imaginem que volem actualitzar `fix-error` per incorporar la història de `main`.

**Que passa si fem un merge en aquesta direcció?**

```         
git switch fix-error
git merge main
```

## Merge de branques: fast-forward {.smaller}

``` tikz
%%| filename: ff-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};
    \node[commit] (H) [right=of E] {H};

    \node[branch] (main) [above=of H] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    \node[head] (head) [above of=main] {HEAD};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (E.east) -- (H.west);
    \draw[->] (G.east) -- (H.west);
    \draw[->] (main) -- (H);
    \draw[->] (fix-error) -- (G);
    \draw[->] (head) -- (main);
\end{tikzpicture}
```

```         
git switch fix-error
git merge main
```

La branca `fix-error` no té cap commit que no tingui `main`. En aquest cas, diem que `fix-error` està endarrere (*behind*) `main`.

**No té sentit crear un commit de merge, no estariem unificant res!**

## Merge de branques: fast-forward {.smaller}

Git ens permet **avançar** la branca `fix-error` fins on fa referència `main`. D'això se'n diu **fast-forward merge**.

``` tikz
%%| filename: ff-3
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};
    \node[commit] (H) [right=of E] {H};

    \node[branch] (main) [above=of H] {main};
    \node[branch] (fix-error) [below=of H] {fix-error};
    \node[head] (head) [below of=fix-error] {HEAD};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (E.east) -- (H.west);
    \draw[->] (G.east) -- (H.west);
    \draw[->] (main) -- (H);
    \draw[->] (fix-error) -- (H);
    \draw[->] (head) -- (fix-error);
\end{tikzpicture}
```

## Rebase de branques

Fins ara hem vist com unificar dues branques amb `merge`.

Però hi ha una altra manera d'incorporar els canvis d'una branca:

**`rebase`**

## Rebase de branques

Tornem a una situació en què tenim dues branques:

``` tikz
%%| filename: rebase-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

`main` ha avançat mentre nosaltres treballàvem a `fix-error`.

**Com podem actualitzar `fix-error` amb els canvis de `main`?**

## Rebase de branques

**Objectiu:** Passar de:

``` tikz
%%| filename: rebase-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

a:

``` tikz
%%| filename: rebase-3
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [right = of E] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (E.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

. . .

**"Apliquem" els commits de `fix-error` sobre els commits de `main`.**

## Rebase de branques {.smaller}

`git rebase main`

Git agafa els commits de `fix-error` que no formen part de `main` i els torna a aplicar, un a un, sobre l'últim commit de `main`.

## **Rebase: els commits canvien**

Els commits de `fix-error` s'han **recreat** a partir de `main`.

Per tant, **no són els mateixos commits** (tenen un ID diferent):

:::: {.columns}

::: {.column width="50%"}

Abans:

``` tikz
%%| filename: rebase-4
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right = of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```
:::

::: {.column width="50%"}

Després:

``` tikz
%%| filename: rebase-5
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F2) [right = of E] {F'};
    \node[commit] (G2) [right=of F2] {G'};
    \node[commit, nearly transparent] (F) [below right = of C] {F};
    \node[commit, nearly transparent] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [above=of G2] {fix-error};
    
    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (E.east) -- (F2.west);
    \draw[->] (F2.east) -- (G2.west);
    \draw[->, nearly transparent] (C.east) -- (F.west);
    \draw[->, nearly transparent] (F.east) -- (G.west);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G2);
\end{tikzpicture}
```
:::

::::

## Merge o rebase?

Podem incorporar els canvis de `main` a `fix-error` de dues maneres.

:::: {.columns}

::: {.column width="50%"}
**Merge:**

``` tikz
%%| filename: merge-vs-rebase-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, above right = of A] (B) {B};
    \node[commit, below right = of A] (C) {C};
    \node[commit, below right = of B] (D) {D};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (A.east) -- (C.west);
    \draw[->] (B.east) -- (D.west);
    \draw[->] (C.east) -- (D.west);
\end{tikzpicture}
```
:::

::: {.column width="50%"}
**Rebase:**

``` tikz
%%| filename: merge-vs-rebase-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, above right = of A] (B) {B};
    \node[commit, below right = of A, nearly transparent] (C) {C};
    \node[commit, right = of B] (C2) {C'};

    \draw[->] (A.east) -- (B.west);
    \draw[->, nearly transparent] (A.east) -- (C.west);
    \draw[->] (B.east) -- (C2.west);
\end{tikzpicture}
```
:::

::::

El **merge** conserva la història tal com ha succeït.

El **rebase** recrea els commits de la branca sobre una nova base i produeix una història lineal.

# Hands-On: Branques

[📄 Laboratori 5: Branques](../laboratori/lab-git-3.html#prepare)

# Conflictes i com resoldre'ls {.smaller}

Fins ara, Git ha pogut unificar les nostres branques automàticament.

Git és capaç de gestionar canvis que no interfereixen entre ells (p.e., una branca edita el fitxer A i l'altra el fitxer B).

També és capaç de gestionar múltiples canvis en un mateix fitxer, sempre que no sigui al mateix lloc (p.e. una branca edita el principi del fitxer A i l'altra el final).

. . .

**Però què passa si les dues branques han modificat la mateixa part d'un fitxer?**

## Conflictes {.smaller}

Imaginem que tenim el fitxer `README.md`:

``` text
Hola!
```

Creem una branca `b1` i modifiquem el fitxer (amb el seu commit corresponent):

``` text
Hola des de b1!
```

Tornem a `main` i també modifiquem el fitxer:

``` text
Hola des de main!
```

El graf de commits ara és:

``` tikz
%%| filename: conflicts-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right = of A] (B) {B};
    \node[commit, below right = of A] (C) {C};
    \node[branch, above = of B] (main) {main};
    \node[branch, below = of C] (b1) {b1};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (A.east) -- (C.west);
    \draw[->] (main.south) -- (B.north);
    \draw[->] (b1.north) -- (C.south);
\end{tikzpicture}
```

I ara procedim a unificar-ho fent un merge des de `b1` cap a `main`.

## Conflictes

Quan fem el merge:

```         
git switch main
git merge b1
```

. . .

Git detecta que hi ha un conflicte!

**Les dues històries han modificat la mateixa part del fitxer**.

```         
CONFLICT (content): Merge conflict in README.md
[...]
```

. . .

Git no fa assumpcions sobre el contingut del fitxer, i per tant **no** pren la decisió per nosaltres.

```         
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
```

## Conflictes

Si executem `git status` veurem que Git ens indica que hi ha fitxers amb conflictes pendents de resoldre:

```         
$ git status
On branch main
You have unmerged paths.
  (fix conflicts and run "git commit")

Unmerged paths:
  (use "git add <file>..." to mark resolution)

    both modified:      README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

## Conflictes

Git modifica el fitxer per indicar-nos on és el conflicte.

Per exemple, `README.md` ara conté:

``` text
<<<<<<< HEAD
Hola des de main!
=======
Hola des de b1!
>>>>>>> b1
```

Les marques indiquen:

```         
<<<<<<< HEAD
canvis de la branca actual (en el exemple: main)
=======
canvis de l'altra branca (en el nostre exemple: b1)
>>>>>>> b1
```

## Resolent el conflicte

Per resoldre el conflicte hem de decidir quin contingut volem.

Podem decidir conservar una versió o l'altra, o una combinació de les dues.

**Editem el fitxer eliminant les marques `<<<<<<< HEAD`, `=======`, i `>>>>>>> b1` i deixant el contingut desitjat.**

Per exemple, editem `README.md` per a que contingui:

``` text
Hola des de main i b1!
```

## Resolent el conflicte

Un cop hem resolt tots els conflictes del fitxer (no hi ha les marques), podem indicar a Git que aquest fitxer està llest.

Per fer-ho, executem `git add <file>`. En el nostre cas, fariem `git add README.md`.

**ALERTA** Git no comprova que, efectivament, haguem resolt el conflicte. Confia en el nostre criteri! Abans de fer `git add`, ens hem d'assegurar que el fitxer és correcte.

## Acabant el merge

Un cop hem resolt tots els conflictes de tots els fitxers, podem continuar amb el nostre merge:

```         
$ git status
On branch main
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

    modified:   README.md
```

Seguint les instruccions que ens dona Git, fem `git commit` per acabar el merge correctament.

::: aside
Si alguna cosa no ens quadra, sempre podem abortar el merge fent servir `git merge --abort`
:::

## Conflictes durant un rebase {.smaller}

Els conflictes també poden aparèixer quan fem un `rebase`.

``` bash
git rebase main
```

Si Git no pot aplicar automàticament un dels commits, el rebase s'atura i ens demana que resolguem el conflicte.

El procés és:

- `git rebase`
- resolem el conflicte
- `git add <file>`
- `git rebase --continue`

. . .

Sempre podem cancel·lar el rebase fent `git rebase --abort`

# Gestió de branques

## Visualitzant branques del repositori

A mesura que un projecte evoluciona, tindrem branques que ja no fem servir (p.e. perquè ja hem fet el *merge*).

Git ens proporciona eines per visualitzar branques:

- `git branch`: mostra la llista de totes les branques (**l'asterisc mostra la branca actual**)
- `git branch -v`: mostra totes les branques i el seu últim commit (amb el missatge)
- `git branch --merged`: mostra les branques que s'ha fet merge cap a la branca actual (també hi ha `--no-merged`)

## Eliminant branques

`git branch -d <branca>`: elimina la branca `<branca>`del repositori

**Nota sobre eliminar branques**: Si intentem eliminar una branca sense que s'hagi fet un merge previ cap a la branca actual, Git ens donarà un error. Si estem segurs d'eliminar la branca, potencialment perdent la feina feta, podem fer servir `git branch -D <branca>`.

## Renombrant branques

`git branch --move <nom vell> <nom nou>`: canvia el nom de la branca.

**Nota:** a continuació veurem que Git ens permet col·laborar amb altres persones. No renombreu branques que s'estiguin fent servir per altres persones.

**Nota 2:** tampoc és recomanable renombrar la branca principal (main/master) sense haver llegit: <https://git-scm.com/book/en/v2/Git-Branching-Branch-Management#_changing_master>

# Hands-On: Branques (part 2)

[📄 Laboratori 5: Branques](../laboratori/lab-git-3.html#prepare)

# GIT és un sistema distribuït

Git és un sistema de control de versions distribuït.

Això significa que cada repositori conté una còpia completa de la història del projecte.

No necessitem estar connectats a Internet per consultar la història, crear commits, crear branques, comparar versions, etc.

. . .

**Però si diverses persones treballen en un mateix projecte, com podem compartir els canvis?**

## Repositori locals i remots

Git no estableix cap repositori com a "central", sinó que els canvis es poden intercanviar entre ells.

```{mermaid}
flowchart LR
    A["Repositori d'Alice"]:::wide
    B["Repositori de Bob"]:::wide
    C["Nostre repositori"]:::wide

    A <--> B
    A <--> C
    B <--> C

    classDef wide padding:100px
```

El nostre repositori s'anomena **local**, i els que es troben en altres sistemes **remots**.

. . .

Durant la vida del projecte, anirem sincronitzant la història del **repositori local** amb la història dels **repositoris remots**.

## Repositoris locals i remots

Alternativament, podem tenir un repositori que utilitzem com a punt de trobada entre diferents persones.

```{mermaid}
flowchart LR
    A["Repositori local<br/>Alice"]:::wide
    B["Repositori remot"]:::wide
    C["Repositori local<br/>Bob"]:::wide

    A <--> B
    B <--> C

    classDef wide padding:100px
```

Aquest repositori remot és un repositori Git normal, **que li donem un ús especial**.

::: aside
Podriem arribar a tenir múltiples repositoris remots, per exemple GitHub i GitLab a la vegada.
:::

## Repositoris remots

Per fer referència a un repositori remot, Git ens permet associar-hi noms.

Per convenció, el repositori remot *"principal"* (p.e. GitHub, GitLab...) s'anomena `origin`.

. . .

Donat el nom, podem referir-nos a les branques del repositori remot.

## **`main` i `origin/main`**

Suposem que tenim un repositori local amb una branca `main` i un repositori remot anomenat `origin`.

::::: columns
::: column
Repositori local:

``` tikz
%%| filename: remotes-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1.5cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[branch] (main) [above=of C] {main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main.south) -- (C.north);
\end{tikzpicture}
```
:::

::: column
Repositori remot:

``` tikz
%%| filename: remotes-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1.5cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[commit, right = of C] (D) {D};
    \node[branch] (main) [above=of D] {main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (main.south) -- (D.north);
\end{tikzpicture}
```
:::
:::::

## `main` i `origin/main`

Un cop hem sincronitzat el repositori remot amb el local, des del repositori local veiem això:

``` tikz
%%| filename: remotes-3
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1.5cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[commit, right = of C] (D) {D};
    \node[branch] (main) [above=of C] {main};
    \node[branch] (omain) [above=of D] {origin/main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (main.south) -- (C.north);
    \draw[->] (omain.south) -- (D.north);
\end{tikzpicture}
```

Tenim dues branques:

- `main`: fa referència a la branca local
- `origin/main`: fa referència a l'estat conegut de la branca `main` al repositori remot `origin`

## `main` i `origin/main`

``` tikz
%%| filename: remotes-3
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1.5cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[commit, right = of C] (D) {D};
    \node[branch] (main) [above=of C] {main};
    \node[branch] (omain) [above=of D] {origin/main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (main.south) -- (C.north);
    \draw[->] (omain.south) -- (D.north);
\end{tikzpicture}
```

Podem fer `merge`, `rebase`, `reset`... fent servir la branca remota per incorporar els seus canvis al nostre repositori local.

. . .

**Però consultar o utilitzar `origin/main` no implica una connexió amb el servidor remot.**

`origin/main` és una referència que tenim dins del nostre repositori local. Per sincronitzar el nostre repositori amb el repositori remot necessitarem comandes noves.

# Interaccionant amb repositoris remots

Les operacions bàsiques són:

- `git clone` Crea un repositori local a partir d'un repositori remot
- `git fetch` Descarrega informació i commits nous del remot
- `git push` Publica els nostres commits al remot
- `git pull` Descarrega els canvis del remot i els integra

## `git clone` {.smaller}

Per començar a treballar amb un projecte que ja existeix en un repositori remot:

`git clone <url>`

Per exemple:

`git clone https://example.com/projecte.git`

Git crea un nou directori amb:

- els fitxers del projecte
- tota la història del repositori
- la configuració necessària per interactuar amb el repositori remot

::: aside
El directori creat té el nom del projecte. Podem canviar-lo fent servir `git clone <url> <directori>`.
:::

## `git push` {.smaller}

Imaginem que hem fet nous commits al nostre repositori local:

::::: columns
::: column
Local:

``` tikz
%%| filename: push-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of C] (main) {main};
    \node[branch, below = of B] (omain) {origin/main};

    \draw[->] (A) -- (B);
    \draw[->] (B) -- (C);
    \draw[->] (main) -- (C);
    \draw[->] (omain) -- (B);
\end{tikzpicture}
```
:::

::: column
Remot:

``` tikz
%%| filename: push-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[branch, below = of B] (main) {main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (main) -- (B);
\end{tikzpicture}
```
:::
:::::

Podem publicar els nostres commits al repositori remot amb `git push`:

::::: columns
::: column
Local:

``` tikz
%%| filename: push-3
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of C] (main) {main};
    \node[branch, above = of C] (omain) {origin/main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main) -- (C);
    \draw[->] (omain) -- (C);
\end{tikzpicture}
```
:::

::: column
Remot:

``` tikz
%%| filename: push-4
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of C] (main) {main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main.north) -- (C.south);
\end{tikzpicture}
```
:::
:::::

push **envia els nostres commits al repositori remot**.

## `git fetch` {.smaller}

Ara imaginem la situació contrària: algú ha publicat nous commits al repositori remot:

::::: columns
::: column
Local:

``` tikz
%%| filename: fetch-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[branch, below = of B] (main) {main};
    \node[branch, above = of B] (omain) {origin/main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (main) -- (B);
    \draw[->] (omain) -- (B);
\end{tikzpicture}
```
:::

::: column
Remot:

``` tikz
%%| filename: fetch-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of C] (main) {main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main.north) -- (C.south);
\end{tikzpicture}
```
:::
:::::

Podem descarregar aquests nous commits amb `git fetch`:

::::: columns
::: column
Local:

``` tikz
%%| filename: fetch-3
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of B] (main) {main};
    \node[branch, below = of C] (omain) {origin/main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main) -- (B);
    \draw[->] (omain) -- (C);
\end{tikzpicture}
```
:::

::: column
Remot:

``` tikz
%%| filename: fetch-4
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of C] (main) {main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main.north) -- (C.south);
\end{tikzpicture}
```
:::
:::::

fetch **descarrega els canvis, però no modifica la nostra branca actual**.

## `git pull`

Hem vist que `git fetch` descarrega els nous commits del repositori remot, però no modifica la nostra branca actual.

Si volem descarregar els canvis i integrar-los directament a la nostra branca actual, podem fer servir `git pull`

. . .

`git pull` combina dues operacions:

1.  `git fetch`
2.  `git merge`

Per exemple, si estem a `main`, `git pull` seria equivalent conceptualment a: 1. `git fetch` 2. `git merge origin/main`

## `git pull`

::::: columns
::: column
Local:

``` tikz
%%| filename: pull-1
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[branch, below = of B] (main) {main};
    \node[branch, above = of B] (omain) {origin/main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (main) -- (B);
    \draw[->] (omain) -- (B);
\end{tikzpicture}
```
:::

::: column
Remot:

``` tikz
%%| filename: pull-2
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of C] (main) {main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main.north) -- (C.south);
\end{tikzpicture}
```
:::
:::::

`git pull`

::::: columns
::: column
Local:

``` tikz
%%| filename: pull-3
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of C] (main) {main};
    \node[branch, above = of C] (omain) {origin/main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main) -- (C);
    \draw[->] (omain) -- (C);
\end{tikzpicture}
```
:::

::: column
Remot:

``` tikz
%%| filename: pull-4
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm and 1.5cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit, right=of A] (B) {B};
    \node[commit, right=of B] (C) {C};
    \node[branch, below = of C] (main) {main};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (main.north) -- (C.south);
\end{tikzpicture}
```
:::
:::::

## Conflictes amb remots {.smaller}

Degut a que la història del repositori remot pot divergir de la nostra, podem trobar-nos amb aquestes situacions:

- Quan fem `push`, el repositori remot ens pot rebutjar l'operació perquè la branca remota té commits que nosaltres no tenim.
- Quan fem `pull`, els canvis remots i locals poden haver divergit. En aquest cas, la integració pot requerir un `merge` o un `rebase` i, si hi ha conflictes, Git aturarà l'operació perquè els solucionem.

. . .

Per evitar sorpreses, és recomanable actualitzar sovint la informació del nostre repositori sobre els remots amb `git fetch` i integrar els canvis remots regularment.

# Recap {.smaller}

Hem après a treballar amb diferents línies de la història d'un projecte:

``` tikz
%%| filename: commits-tags-branches
\usetikzlibrary{positioning}
\begin{tikzpicture}[
    node distance=1cm,
    commit/.style={draw, rectangle, rounded corners, align=center, fill=green!30},
    head/.style={draw, rectangle, rounded corners, align=center, fill=red!30},
    tag/.style={draw, rectangle, rounded corners, align=center, fill=gray!30, font=\small},
    branch/.style={draw, rectangle, rounded corners, align=center, fill=orange!30}
]
    \node[commit] (A) {A};
    \node[commit] (B) [right=of A] {B};
    \node[commit] (C) [right=of B] {C};
    \node[commit] (D) [right=of C] {D};
    \node[commit] (E) [right=of D] {E};
    \node[commit] (F) [below right=of C] {F};
    \node[commit] (G) [right=of F] {G};

    \node[branch] (main) [above=of E] {main};
    \node[branch] (fix-error) [below=of G] {fix-error};
    
    \node[tag] (v1) [above = of C] {v1.0};

    \draw[->] (A.east) -- (B.west);
    \draw[->] (B.east) -- (C.west);
    \draw[->] (C.east) -- (D.west);
    \draw[->] (D.east) -- (E.west);
    \draw[->] (C.east) -- (F.west);
    \draw[->] (F.east) -- (G.west);
    \draw[->] (v1) -- (C);
    \draw[->] (main) -- (E);
    \draw[->] (fix-error) -- (G);
\end{tikzpicture}
```

Una **branca** ens permet desenvolupar diferents camins a partir d'una mateixa història.

Podem tornar a unificar aquests camins amb **merge** o reorganitzar-los amb **rebase**, tot i que a vegades hem de **resoldre els conflictes**.

. . .

Els commits poden tenir noms fàcils de recordar mitjançant **tags**, i les **branques** són referències que avancen a mesura que fem nous commits.

## Recap {.smaller}

Git és distribuït: cada repositori té la seva pròpia còpia de la història.

```{mermaid}
flowchart LR
    A["Repositori local"] <--> B["Repositori remot"]
```

Podem sincronitzar els repositoris amb:

- git fetch
- git pull
- git push

I quan les històries divergeixen, Git ens pot demanar que integrem els canvis o que resolguem conflictes.

# Material addicional

- Llibre de Git: <https://git-scm.com/book/en/v2>
- The Missing Semester: <https://missing.csail.mit.edu/2020/version-control/>
- Joc interactiu: LearnGitBranching <https://learngitbranching.js.org/>